"""`strategy export --ctx <dir>` — positions as a ctx decisions corpus.

The store (`STRATEGY_DB_URL`) stays the writer. This module only reads it and
writes markdown; it is regenerated on every call and must never be hand-edited
— the same trap `docs/OPERATING-NOTES.md` records for `memo_prose.yaml`: a
hand-written correction here would look current and drift silently, because
nothing re-derives it from the store. This IS the decisions corpus (plan
Phase 3, hq-sl5k) — do not grow a second one; `ctx` indexes what this writes.

Status mapping (store -> ctx). ctx's decisions type gives exactly one status
string a meaning of its own: `query.py`'s default filter passes only NULL or
`"accepted"`, and `lint.py` only special-cases `"accepted"` (an accepted doc
that something else claims to supersede is an error). Every other status is
equivalent, to ctx, to "not a settled decision — needs `ctx get --history`".
So only a position the store considers actually decided maps onto it; the
rest get distinct, honest labels rather than reusing "accepted" or inventing
a value ctx has no opinion about:

    resolved  -> accepted    (decided; visible in `ctx get` by default)
    holding   -> proposed    (still open; needs --history)
    contested -> contested   (disputed; needs --history)
    retired   -> retired     (no longer held; needs --history)

One override on top of that table: the store's `status` and its supersession
link are independent columns (`supersede()` in core.py never touches `status`),
so a position can sit `resolved` in the store — correctly, at the time it was
decided — years after something else superseded it. Exported as-is that is
`status: accepted` on a doc `ctx lint` can see is superseded, which is exactly
the contradiction the decisions lint rejects (and did, on the first real run
against all 112 positions: dozens of `resolved`-but-superseded rows). So any
position with a `superseded_by_id` is exported as `status: superseded`
regardless of what STATUS_MAP would otherwise say — true either way, and the
one value ctx already treats as "not current" without being told anything else
about it.
"""

from __future__ import annotations

import dataclasses
import fnmatch
import re
from pathlib import Path

import yaml
from sqlalchemy import select

from . import db
from .models import Evidence, Position

STATUS_MAP: dict[str, str] = {
    "resolved": "accepted",
    "holding": "proposed",
    "contested": "contested",
    "retired": "retired",
}

FILE_GLOB = "pos-*.md"

# ctx (hq-sl5k, ctx side) now excludes `README.md` from every corpus by
# default — indexing, lint, and the staleness fingerprint alike — so this
# file needs no frontmatter at all, fake or otherwise. It carries only the
# marker line below (checked verbatim by `_validate_target_dir`, which is
# how `export_ctx` recognizes a directory as its own on a later run) and the
# regenerate instructions. If a rig's ctx is old enough to lack `exclude:`,
# a plain README with no frontmatter block is invisible to `iter_corpus_files`
# only once that ships — until then it would show up as an unindexed, unlinted
# extra `.md` file, which is still better than a fake "decision".
GENERATOR_MARKER = "<!-- generated by strategy export --ctx; do not edit -->"
# The round-1 (bdc0284) README opened with fake decision frontmatter whose
# `title:` was exactly this (`git show bdc0284:src/strategy_store/ctx_export.py`
# — line 3 of the file, well inside the 10-line window checked below).
# `_validate_target_dir` accepts a README carrying it as its own prior export
# too, so a round-1-shaped directory upgrades to the marker form on the next
# export instead of being refused with no path forward.
ROUND1_MARKER_TEXT = "Generated by strategy export --ctx — do not edit"
README_TEXT = f"""\
{GENERATOR_MARKER}

# decisions

Generated by `strategy export --ctx <dir>`. Do not edit these files — they are
regenerated on every export from the strategy store (`STRATEGY_DB_URL`), and a
hand fix here is silently overwritten the next time someone runs it. Change the
position in the store instead (`strategy set`, `strategy supersede`,
`strategy evidence add`), then re-run the export.

One file per position, named `pos-<id>.md`. `ctx` indexes this directory as a
`decisions` corpus (`exclude: ["README.md"]` keeps this file out of it); see
`~/gt/docs/plans/ctx-context-retrieval.md` §Schema for the frontmatter
contract and `src/strategy_store/ctx_export.py` for the status mapping
(store status -> ctx status).
"""


class TargetDirNotOwnedError(RuntimeError):
    """`export_ctx` refused to write into a directory it doesn't recognize as
    its own — see `_validate_target_dir`."""


def _validate_target_dir(dir_path: Path) -> None:
    """Refuse to touch `dir_path` unless it's new, empty, or already looks
    like a strategy `export --ctx` target: only `pos-*.md` files and, if
    present, a `README.md` that is either this export's own (first line
    exactly `GENERATOR_MARKER`) or a round-1-shaped one (carries
    `ROUND1_MARKER_TEXT` in its first 10 lines) — the latter is upgraded to
    the marker form for free by `export_ctx`'s own unconditional README
    rewrite once validation passes, so accepting it here is what gives a
    round-1 directory a path forward instead of a permanent refusal.

    The marker is an ownership signal, not a lock: a hand-written README
    whose first line happens to equal `GENERATOR_MARKER` verbatim would be
    accepted (and then overwritten) too. Accepted as a real but narrow risk
    — the string is distinctive enough that no plausible hand-written first
    line collides with it by accident.

    Found by review (hq-sl5k): `export_ctx --ctx <wrong-dir>` used to
    overwrite any `README.md` already there unconditionally — a hand-written
    README in an unrelated directory, gone, no confirmation. This runs before
    anything is created, deleted, or written; on refusal, nothing changes."""
    if not dir_path.exists() or not any(dir_path.iterdir()):
        return
    offending = []
    for entry in sorted(dir_path.iterdir()):
        if entry.is_dir():
            offending.append(entry.name)
            continue
        if entry.name == "README.md":
            text = entry.read_text(encoding="utf-8")
            first_line = text.splitlines()[:1]
            if first_line == [GENERATOR_MARKER]:
                continue
            head = "\n".join(text.splitlines()[:10])
            if ROUND1_MARKER_TEXT in head:
                continue
            offending.append(entry.name)
            continue
        if fnmatch.fnmatch(entry.name, FILE_GLOB):
            continue
        offending.append(entry.name)
    if offending:
        raise TargetDirNotOwnedError(
            f"{dir_path} is not empty and doesn't look like a strategy "
            f"export --ctx target — refusing to write, nothing changed. "
            f"Unexpected entries: {', '.join(offending)}"
        )


def ctx_id(position_id: int) -> str:
    return f"pos-{position_id}"


def _one_liner(statement: str | None) -> str | None:
    """The position's own first paragraph, used verbatim as ctx's `summary`
    — never generated (frontmatter.py's rule, restated in the plan).
    "First paragraph" is text up to the first blank line, its own internal
    newlines joined with a space; this is selection, not generation — the
    words are exactly what's in the store, in the order they appear.

    Originally required the whole statement to be a single physical line,
    which lost the summary for any hard-wrapped paragraph (63 of 112 real
    positions, on the first export — review finding hq-sl5k). Only an
    actually empty statement has no usable one-liner now; that case still
    returns None so callers omit `summary` and `ctx lint` flags the gap
    rather than a sentence getting manufactured for it."""
    text = (statement or "").strip()
    if not text:
        return None
    # Normalize line endings before splitting on a blank line: a CRLF
    # (`\r\n\r\n`) or bare-CR blank line otherwise slips past `\n[ \t]*\n`
    # entirely, so a two-paragraph CRLF statement exported both paragraphs
    # into `summary` (review finding, hq-sl5k round 2 — reproduced).
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    first_paragraph = re.split(r"\n[ \t]*\n", text, maxsplit=1)[0]
    joined = " ".join(line.strip() for line in first_paragraph.splitlines())
    return joined.strip() or None


def _date_for(p: Position) -> str | None:
    if p.decided_on:
        return p.decided_on.isoformat()
    if p.created_at:
        return p.created_at.date().isoformat()
    return None


def _tags_for(p: Position) -> list[str]:
    tags = []
    if p.venture:
        tags.append(p.venture)
    if p.element_key:
        tags.append(p.element_key)
    return tags


@dataclasses.dataclass
class ExportedDoc:
    id: str
    filename: str
    frontmatter: dict
    text: str
    has_summary: bool


def _ctx_status(p: Position, superseded_by_ids: list[str]) -> str:
    if superseded_by_ids:
        return "superseded"
    return STATUS_MAP.get(p.status, p.status)


def _frontmatter_for(p: Position, supersedes_ids: list[str], superseded_by_ids: list[str]) -> dict:
    fm: dict = {
        "id": ctx_id(p.id),
        "title": p.title,
    }
    summary = _one_liner(p.statement)
    if summary is not None:
        fm["summary"] = summary
    fm["status"] = _ctx_status(p, superseded_by_ids)
    date_value = _date_for(p)
    if date_value is not None:
        fm["date"] = date_value
    fm["supersedes"] = supersedes_ids
    fm["superseded-by"] = superseded_by_ids
    fm["tags"] = _tags_for(p)
    fm["terms"] = []
    return fm


def _body_for(p: Position, evidence: list[Evidence]) -> str:
    lines = [f"# {p.title}", ""]
    statement = (p.statement or "").strip()
    lines.append(statement if statement else "(no statement recorded in the store)")
    lines.append("")
    lines.append("## Evidence")
    if not evidence:
        lines.append("")
        lines.append("(none recorded)")
    else:
        lines.append("")
        for e in evidence:
            when = e.observed_on.isoformat() if e.observed_on else "undated"
            lines.append(f"- {when} — {e.source} ({e.scope}): {e.summary}")
    lines.append("")
    return "\n".join(lines)


def _render(doc_frontmatter: dict, body: str) -> str:
    fm_text = yaml.safe_dump(
        doc_frontmatter, sort_keys=False, default_flow_style=False, allow_unicode=True
    )
    return f"---\n{fm_text}---\n\n{body}"


@dataclasses.dataclass
class ExportStats:
    written: int
    removed: list[str]
    missing_summary: list[str]


def build_docs(session) -> list[ExportedDoc]:
    """All positions, oldest id first, rendered as ctx decisions docs.

    Reads every position, including superseded and retired ones — the walker
    ctx builds on top of this (plan Phase 3) needs the whole supersession
    chain, not just what is currently live."""
    positions = list(session.scalars(select(Position).order_by(Position.id)))
    docs = []
    for p in positions:
        supersedes_ids = [ctx_id(q.id) for q in sorted(p.supersedes, key=lambda q: q.id)]
        superseded_by_ids = [ctx_id(p.superseded_by_id)] if p.superseded_by_id else []
        fm = _frontmatter_for(p, supersedes_ids, superseded_by_ids)
        evidence = list(
            session.scalars(
                select(Evidence)
                .where(Evidence.position_id == p.id)
                .order_by(Evidence.observed_on, Evidence.id)
            )
        )
        body = _body_for(p, evidence)
        text = _render(fm, body)
        docs.append(
            ExportedDoc(
                id=fm["id"],
                filename=f"{fm['id']}.md",
                frontmatter=fm,
                text=text,
                has_summary="summary" in fm,
            )
        )
    return docs


def export_ctx(dir_path: Path) -> ExportStats:
    """Write one markdown file per position into `dir_path`, plus a README
    header, and delete any `pos-*.md` file for a position no longer in the
    store — the directory mirrors the store. Deterministic: the same store
    state produces byte-identical files every time (no timestamps, sorted by
    id).

    Refuses (`TargetDirNotOwnedError`, nothing written) if `dir_path` is
    non-empty and doesn't already look like a strategy export --ctx target —
    see `_validate_target_dir`."""
    _validate_target_dir(dir_path)
    dir_path.mkdir(parents=True, exist_ok=True)
    db.init_db()
    with db.session() as s:
        docs = build_docs(s)

    current_filenames = {d.filename for d in docs}
    stale = [p for p in dir_path.glob(FILE_GLOB) if p.name not in current_filenames]
    removed = sorted(p.name for p in stale)
    for p in stale:
        p.unlink()

    missing_summary = []
    for d in docs:
        (dir_path / d.filename).write_text(d.text, encoding="utf-8")
        if not d.has_summary:
            missing_summary.append(d.id)

    (dir_path / "README.md").write_text(README_TEXT, encoding="utf-8")

    return ExportStats(written=len(docs), removed=removed, missing_summary=missing_summary)
