"""Database helpers for MCP server — generated by SEA crab."""

import os
from pathlib import Path

import psycopg2
import psycopg2.extras

# Baked in by SEA at generation time.
# DSN uses a scoped Crab role — NOT the SEA admin connection.
# Schema matches the database GRANTs for this role.
_DEFAULT_DSN = ""
_DEFAULT_DB_SCHEMA = ""
# The project's own env var for this database, if it has one — so the server
# reads the same connection string its CLI does instead of a second copy.
_DSN_ENV = "STRATEGY_DB_URL"
_PROJECT_JSON = Path(__file__).resolve().parent.parent / ".sea" / "project.json"


class NoDatabase(RuntimeError):
    """No connection string resolved. Raised instead of handing psycopg2 an
    empty DSN, which makes it connect to the LOCAL DEFAULT database — a
    different store than the one this server was generated for, with nothing
    to tell the caller."""


def _load_config() -> tuple[str, str]:
    """Resolve DSN and DB schema at runtime.

    Priority:
      1. CRAB_DATABASE_URL, then the project's own DSN env var if one was named
      2. connection.json crab_roles entry (updated whenever viz server regenerates Crab)
      3. Baked-in defaults (set at generation time)
    """
    for var in ("CRAB_DATABASE_URL", _DSN_ENV):
        if var and os.environ.get(var):
            return os.environ[var], _DEFAULT_DB_SCHEMA
    try:
        import json as _j
        conn_path = _PROJECT_JSON.parent / "connection.json"
        if conn_path.exists():
            conn = _j.loads(conn_path.read_text())
            primary_schema = _DEFAULT_DB_SCHEMA.split(",")[0].strip()
            entry = conn.get("crab_roles", {}).get(primary_schema, {})
            if entry.get("crab_dsn"):
                return entry["crab_dsn"], _DEFAULT_DB_SCHEMA
    except (OSError, ValueError):
        pass
    return _DEFAULT_DSN, _DEFAULT_DB_SCHEMA


DSN, DB_SCHEMA = _load_config()

FK_JOINS = {'evidence': [{'fk_field': 'position_id', 'target_col': 'id', 'target_table': 'positions'}],
 'forcing': [{'fk_field': 'position_id', 'target_col': 'id', 'target_table': 'positions'}],
 'metric_readings': [{'fk_field': 'metric_id', 'target_col': 'id', 'target_table': 'metrics'}],
 'metrics': [{'fk_field': 'position_id', 'target_col': 'id', 'target_table': 'positions'}],
 'positions': [{'fk_field': 'supersedes_id', 'target_col': 'id', 'target_table': 'positions'}]}

CHILDREN = {'metrics': [{'child_table': 'metric_readings', 'fk_field': 'metric_id'}],
 'positions': [{'child_table': 'positions', 'fk_field': 'supersedes_id'},
               {'child_table': 'evidence', 'fk_field': 'position_id'},
               {'child_table': 'forcing', 'fk_field': 'position_id'},
               {'child_table': 'metrics', 'fk_field': 'position_id'}]}

SCHEMA_INFO = {'assessments': {'fields': [{'name': 'id', 'pk': True, 'type': 'int'},
                            {'name': 'framework', 'pk': False, 'type': 'string'},
                            {'name': 'test_key', 'pk': False, 'type': 'string'},
                            {'name': 'venture', 'pk': False, 'type': 'string'},
                            {'name': 'verdict', 'pk': False, 'type': 'string'},
                            {'name': 'note', 'pk': False, 'type': 'text'},
                            {'name': 'scope', 'pk': False, 'type': 'string'},
                            {'name': 'decided_on', 'pk': False, 'type': 'date'},
                            {'name': 'created_at', 'pk': False, 'type': 'datetime'}],
                 'model': 'Assessment'},
 'drops': {'fields': [{'name': 'id', 'pk': True, 'type': 'int'},
                      {'name': 'posted_on', 'pk': False, 'type': 'date'},
                      {'name': 'url', 'pk': False, 'type': 'string'},
                      {'name': 'activity_id', 'pk': False, 'type': 'string'},
                      {'name': 'share_id', 'pk': False, 'type': 'string'},
                      {'name': 'title', 'pk': False, 'type': 'string'},
                      {'name': 'format', 'pk': False, 'type': 'string'},
                      {'name': 'app_url', 'pk': False, 'type': 'string'},
                      {'name': 'impressions', 'pk': False, 'type': 'int'},
                      {'name': 'reached', 'pk': False, 'type': 'int'},
                      {'name': 'article_views', 'pk': False, 'type': 'int'},
                      {'name': 'email_sends', 'pk': False, 'type': 'int'},
                      {'name': 'reactions', 'pk': False, 'type': 'int'},
                      {'name': 'comments', 'pk': False, 'type': 'int'},
                      {'name': 'reposts', 'pk': False, 'type': 'int'},
                      {'name': 'saves', 'pk': False, 'type': 'int'},
                      {'name': 'link_clicks', 'pk': False, 'type': 'int'},
                      {'name': 'followers_gained', 'pk': False, 'type': 'int'},
                      {'name': 'own_comments', 'pk': False, 'type': 'int'},
                      {'name': 'own_reposts', 'pk': False, 'type': 'int'},
                      {'name': 'stats_as_of', 'pk': False, 'type': 'date'},
                      {'name': 'notes', 'pk': False, 'type': 'text'},
                      {'name': 'created_at', 'pk': False, 'type': 'datetime'}],
           'model': 'Drop'},
 'evidence': {'fields': [{'name': 'id', 'pk': True, 'type': 'int'},
                         {'name': 'position_id', 'pk': False, 'type': 'int'},
                         {'name': 'source', 'pk': False, 'type': 'string'},
                         {'name': 'scope', 'pk': False, 'type': 'string'},
                         {'name': 'observed_on', 'pk': False, 'type': 'date'},
                         {'name': 'summary', 'pk': False, 'type': 'text'},
                         {'name': 'created_at', 'pk': False, 'type': 'datetime'}],
              'model': 'Evidence'},
 'forcing': {'fields': [{'name': 'id', 'pk': True, 'type': 'int'},
                        {'name': 'title', 'pk': False, 'type': 'string'},
                        {'name': 'condition', 'pk': False, 'type': 'text'},
                        {'name': 'due_on', 'pk': False, 'type': 'date'},
                        {'name': 'gates', 'pk': False, 'type': 'text'},
                        {'name': 'resolved_on', 'pk': False, 'type': 'date'},
                        {'name': 'position_id', 'pk': False, 'type': 'int'},
                        {'name': 'source_system', 'pk': False, 'type': 'string'},
                        {'name': 'source_ref', 'pk': False, 'type': 'string'},
                        {'name': 'venture', 'pk': False, 'type': 'string'},
                        {'name': 'created_at', 'pk': False, 'type': 'datetime'}],
             'model': 'Forcing'},
 'metric_readings': {'fields': [{'name': 'id', 'pk': True, 'type': 'int'},
                                {'name': 'metric_id', 'pk': False, 'type': 'int'},
                                {'name': 'as_of', 'pk': False, 'type': 'date'},
                                {'name': 'value', 'pk': False, 'type': 'int'},
                                {'name': 'origin', 'pk': False, 'type': 'string'},
                                {'name': 'note', 'pk': False, 'type': 'text'},
                                {'name': 'created_at', 'pk': False, 'type': 'datetime'}],
                     'model': 'MetricReading'},
 'metrics': {'fields': [{'name': 'id', 'pk': True, 'type': 'int'},
                        {'name': 'name', 'pk': False, 'type': 'string'},
                        {'name': 'title', 'pk': False, 'type': 'string'},
                        {'name': 'beat', 'pk': False, 'type': 'string'},
                        {'name': 'source', 'pk': False, 'type': 'string'},
                        {'name': 'source_key', 'pk': False, 'type': 'string'},
                        {'name': 'cadence', 'pk': False, 'type': 'string'},
                        {'name': 'gates', 'pk': False, 'type': 'string'},
                        {'name': 'due_on', 'pk': False, 'type': 'date'},
                        {'name': 'position_id', 'pk': False, 'type': 'int'},
                        {'name': 'notes', 'pk': False, 'type': 'text'},
                        {'name': 'created_at', 'pk': False, 'type': 'datetime'}],
             'model': 'Metric'},
 'positions': {'fields': [{'name': 'id', 'pk': True, 'type': 'int'},
                          {'name': 'title', 'pk': False, 'type': 'string'},
                          {'name': 'statement', 'pk': False, 'type': 'text'},
                          {'name': 'element_key', 'pk': False, 'type': 'string'},
                          {'name': 'status', 'pk': False, 'type': 'string'},
                          {'name': 'scope', 'pk': False, 'type': 'string'},
                          {'name': 'decided_on', 'pk': False, 'type': 'date'},
                          {'name': 'venture', 'pk': False, 'type': 'string'},
                          {'name': 'source_system', 'pk': False, 'type': 'string'},
                          {'name': 'source_ref', 'pk': False, 'type': 'string'},
                          {'name': 'source_status', 'pk': False, 'type': 'string'},
                          {'name': 'supersedes_id', 'pk': False, 'type': 'int'},
                          {'name': 'claim_key', 'pk': False, 'type': 'string'},
                          {'name': 'synced_at', 'pk': False, 'type': 'datetime'},
                          {'name': 'created_at', 'pk': False, 'type': 'datetime'}],
               'model': 'Position'}}


def _connect():
    if not DSN:
        raise NoDatabase(
            "no connection string: set CRAB_DATABASE_URL, or regenerate with --dsn. "
            "Refusing to connect with an empty DSN, which would open the local "
            "default database instead."
        )
    conn = psycopg2.connect(DSN)
    if DB_SCHEMA:
        with conn.cursor() as cur:
            cur.execute(f"SET search_path TO {DB_SCHEMA}")
    return conn


_ALLOWED_OPS = {"=", "!=", ">", "<", ">=", "<=", "LIKE", "ILIKE", "IN", "IS NULL", "IS NOT NULL"}


def _valid_columns(table: str) -> set[str]:
    """Return valid column names for a table from SCHEMA metadata."""
    if table not in SCHEMA_INFO:
        return set()
    return {f["name"] for f in SCHEMA_INFO[table]["fields"]}


async def query_table(
    table: str,
    filters: list[dict] | None = None,
    order_by: str = "id",
    order_dir: str = "ASC",
    limit: int = 20,
    include_related: bool = True,
) -> list[dict]:
    """Query a table with structured filters, validated ORDER BY, and FK joins."""
    from psycopg2 import sql as psql

    valid_cols = _valid_columns(table)
    select_cols = [f"{table}.*"]
    join_clauses = []

    if include_related and table in FK_JOINS:
        for join in FK_JOINS[table]:
            target = join["target_table"]
            fk = join["fk_field"]
            tcol = join["target_col"]
            join_clauses.append(
                f"LEFT JOIN {target} ON {table}.{fk} = {target}.{tcol}"
            )

    sql = f"SELECT {', '.join(select_cols)} FROM {table}"
    if join_clauses:
        sql += " " + " ".join(join_clauses)

    # Build parameterized WHERE from structured filters
    params = []
    where_parts = []
    for f in (filters or []):
        col = f.get("column", "")
        op = f.get("op", "").upper()
        val = f.get("value")
        if col not in valid_cols or op not in _ALLOWED_OPS:
            continue
        if op in ("IS NULL", "IS NOT NULL"):
            where_parts.append(f"{table}.{col} {op}")
        elif op == "IN":
            in_vals = [v.strip() for v in str(val).split(",") if v.strip()]
            if not in_vals:
                continue
            placeholders = ", ".join(["%s"] * len(in_vals))
            where_parts.append(f"{table}.{col} IN ({placeholders})")
            params.extend(in_vals)
        else:
            where_parts.append(f"{table}.{col} {op} %s")
            params.append(val)

    if where_parts:
        sql += " WHERE " + " AND ".join(where_parts)

    # Validated order_by — must be a known column
    if order_by not in valid_cols:
        order_by = "id"
    if order_dir.upper() not in ("ASC", "DESC"):
        order_dir = "ASC"
    sql += f" ORDER BY {table}.{order_by} {order_dir.upper()} LIMIT %s"
    params.append(min(limit, 100))

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, params)
            rows = [dict(r) for r in cur.fetchall()]
            for row in rows:
                for k, v in row.items():
                    if not isinstance(v, (str, int, float, bool, type(None))):
                        row[k] = str(v)
            return rows


def _validate_fks(table: str, data: dict, conn) -> str | None:
    """Check that FK values in data exist in their target tables.

    Returns an error message string if validation fails, or None if OK.
    """
    joins = FK_JOINS.get(table, [])
    if not joins:
        return None
    with conn.cursor() as cur:
        for join in joins:
            fk_field = join["fk_field"]
            if fk_field not in data:
                continue
            val = data[fk_field]
            if val is None:
                continue  # nullable FK
            target_table = join["target_table"]
            target_col = join["target_col"]
            cur.execute(
                f"SELECT 1 FROM {target_table} WHERE {target_col} = %s LIMIT 1",
                [val],
            )
            if not cur.fetchone():
                return f"FK violation: {fk_field}={val} not found in {target_table}.{target_col}"
    return None


async def insert_row(table: str, data: dict) -> dict:
    """Insert a row and return the created record."""
    cols = list(data.keys())
    vals = list(data.values())
    placeholders = ", ".join(["%s"] * len(cols))
    col_names = ", ".join(cols)

    sql = f"INSERT INTO {table} ({col_names}) VALUES ({placeholders}) RETURNING *"

    with _connect() as conn:
        fk_err = _validate_fks(table, data, conn)
        if fk_err:
            return {"error": fk_err}
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, vals)
            conn.commit()
            row = dict(cur.fetchone())
            for k, v in row.items():
                if not isinstance(v, (str, int, float, bool, type(None))):
                    row[k] = str(v)
            return row


async def batch_insert(table: str, rows: list[dict]) -> list[dict]:
    """Insert multiple rows into a table in one transaction."""
    if not rows:
        return {"error": "No rows to insert"}
    results = []
    with _connect() as conn:
        # Validate all rows before inserting any
        for i, data in enumerate(rows):
            fk_err = _validate_fks(table, data, conn)
            if fk_err:
                return {"error": f"Row {i}: {fk_err}"}
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            for data in rows:
                cols = list(data.keys())
                vals = list(data.values())
                placeholders = ", ".join(["%s"] * len(cols))
                col_names = ", ".join(cols)
                sql = f"INSERT INTO {table} ({col_names}) VALUES ({placeholders}) RETURNING *"
                cur.execute(sql, vals)
                row = dict(cur.fetchone())
                for k, v in row.items():
                    if not isinstance(v, (str, int, float, bool, type(None))):
                        row[k] = str(v)
                results.append(row)
            conn.commit()
    return results


async def insert_with_children(table: str, data: dict, children: dict) -> dict:
    """Insert a parent row and its children in one transaction.

    The parent's new ID is auto-filled into each child row's FK field.
    children is a dict of {child_table: [row_dicts]}.
    """
    child_results = {}
    with _connect() as conn:
        # Validate parent FKs
        fk_err = _validate_fks(table, data, conn)
        if fk_err:
            return {"error": f"Parent: {fk_err}"}

        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            # Insert parent
            cols = list(data.keys())
            vals = list(data.values())
            placeholders = ", ".join(["%s"] * len(cols))
            col_names = ", ".join(cols)
            sql = f"INSERT INTO {table} ({col_names}) VALUES ({placeholders}) RETURNING *"
            cur.execute(sql, vals)
            parent_row = dict(cur.fetchone())
            parent_id = parent_row.get("id")

            # Insert children, auto-filling FK
            for child_table, child_rows in children.items():
                # Find the FK field that points to this parent
                fk_field = None
                for child_info in CHILDREN.get(table, []):
                    if child_info["child_table"] == child_table:
                        fk_field = child_info["fk_field"]
                        break
                if not fk_field:
                    child_results[child_table] = {"error": f"No FK from {child_table} to {table}"}
                    continue

                inserted = []
                for cdata in child_rows:
                    cdata[fk_field] = parent_id
                    # Validate non-parent FKs on child row
                    fk_err = _validate_fks(child_table, cdata, conn)
                    if fk_err:
                        child_results[child_table] = {"error": fk_err}
                        break
                    ccols = list(cdata.keys())
                    cvals = list(cdata.values())
                    cph = ", ".join(["%s"] * len(ccols))
                    ccn = ", ".join(ccols)
                    csql = f"INSERT INTO {child_table} ({ccn}) VALUES ({cph}) RETURNING *"
                    cur.execute(csql, cvals)
                    crow = dict(cur.fetchone())
                    for k, v in crow.items():
                        if not isinstance(v, (str, int, float, bool, type(None))):
                            crow[k] = str(v)
                    inserted.append(crow)
                else:
                    child_results[child_table] = inserted

            conn.commit()

    for k, v in parent_row.items():
        if not isinstance(v, (str, int, float, bool, type(None))):
            parent_row[k] = str(v)

    return {"parent": parent_row, "children": child_results}


async def update_row(table: str, id: int, data: dict) -> dict:
    """Update a row by ID and return the updated record."""
    if not data:
        return {"error": "No fields to update"}

    set_clause = ", ".join(f"{k} = %s" for k in data.keys())
    vals = list(data.values()) + [id]

    sql = f"UPDATE {table} SET {set_clause} WHERE id = %s RETURNING *"

    with _connect() as conn:
        fk_err = _validate_fks(table, data, conn)
        if fk_err:
            return {"error": fk_err}
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, vals)
            conn.commit()
            row = cur.fetchone()
            if not row:
                return {"error": f"No row with id={id} in {table}"}
            row = dict(row)
            for k, v in row.items():
                if not isinstance(v, (str, int, float, bool, type(None))):
                    row[k] = str(v)
            return row


async def delete_row(table: str, id: int) -> dict:
    """Delete a row by ID."""
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(f"DELETE FROM {table} WHERE id = %s RETURNING id", [id])
            conn.commit()
            deleted = cur.fetchone()
            if not deleted:
                return {"error": f"No row with id={id} in {table}"}
            return {"deleted": True, "table": table, "id": id}


async def get_schema_info(table: str | None = None) -> dict:
    """Return schema information."""
    if table:
        info = SCHEMA_INFO.get(table)
        if not info:
            return {"error": f"Unknown table '{table}'"}
        return {"table": table, **info}
    return {"tables": list(SCHEMA_INFO.keys()), "details": SCHEMA_INFO}
