#!/bin/bash
# MCP Server launcher — generated by SEA crab
# Called by Claude Desktop via WSL

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Credentials come from the environment file, never from the Desktop config.
ENV_FILE="${CRAB_ENV_FILE:-$HOME/.env}"
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
  : "${CRAB_DATABASE_URL:=${STRATEGY_DB_URL:-}}"
  export CRAB_DATABASE_URL
fi

UV="$(command -v uv || echo "$HOME/.local/bin/uv")"
exec "$UV" run server.py
