# /// script
# requires-python = ">=3.11"
# dependencies = ["mcp[cli]>=1.2,<2", "psycopg2-binary"]
# ///
"""MCP server for strategy — generated by SEA crab."""

import json as _json
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from db import query_table, get_schema_info
from mcp.server.fastmcp import FastMCP

TABLES = ["positions", "evidence", "forcing", "assessments", "drops", "metrics", "metric_readings"]
PROJECT_JSON = Path(__file__).resolve().parent.parent / ".sea" / "project.json"


def _read_policy() -> str:
    """Read data policy from project.json at runtime."""
    if PROJECT_JSON.exists():
        try:
            return _json.loads(PROJECT_JSON.read_text()).get("tool_policy", "")
        except Exception:
            pass
    return ""


def _save_policy(policy: str) -> None:
    """Write data policy to project.json."""
    meta = {}
    if PROJECT_JSON.exists():
        try:
            meta = _json.loads(PROJECT_JSON.read_text())
        except Exception:
            pass
    meta["tool_policy"] = policy
    PROJECT_JSON.parent.mkdir(parents=True, exist_ok=True)
    PROJECT_JSON.write_text(_json.dumps(meta, indent=2) + "\n")


server = FastMCP(
    "strategy",
    instructions="""
Database for strategy

IMPORTANT: When the database is empty and data sources are listed above, your FIRST
response should acknowledge the source and offer to populate:
"This schema was built from [source URL]. The database is empty — shall I fetch
that page and populate the tables with real data from it?"
Do NOT wait for the user to ask about data sources. Proactively offer.

This MCP server provides CRUD access to the database.
Always confirm before deleting. Use query to explore data first.

Call get_policy() before any create/update operation to check current data handling rules.
When the user expresses a preference about data handling, call set_policy() to save it.
""",
)


@server.tool()
async def query(
    table: str,
    filters: list[dict] | None = None,
    order_by: str = "id",
    order_dir: str = "ASC",
    limit: int = 20,
    include_related: bool = True,
) -> list[dict]:
    """Query any table in the database.

Use 'filters' for WHERE conditions — each filter is a dict with 'column', 'op', and 'value'.
Multiple filters are ANDed together.

Allowed operators: =, !=, >, <, >=, <=, LIKE, ILIKE, IN, IS NULL, IS NOT NULL
For LIKE/ILIKE use % as wildcard. For IN pass value as comma-separated string.
For IS NULL / IS NOT NULL, omit the value field.

Tables:
  positions — id (PK, required), title (required), statement (required), element_key, status (required), scope (required), decided_on, venture, source_system (required), source_ref (required), source_status, supersedes_id (FK->positions.id), claim_key, synced_at, created_at (required)
  evidence — id (PK, required), position_id (FK->positions.id, required), source (required), scope (required), observed_on, summary (required), created_at (required)
  forcing — id (PK, required), title (required), condition (required), due_on, gates (required), resolved_on, position_id (FK->positions.id), source_system (required), source_ref (required), venture, created_at (required)
  assessments — id (PK, required), framework (required), test_key (required), venture (required), verdict (required), note (required), scope (required), decided_on, created_at (required)
  drops — id (PK, required), posted_on (required), url (required), activity_id, share_id, title (required), format (required), app_url, impressions, reached, article_views, email_sends, reactions, comments, reposts, saves, link_clicks, followers_gained, own_comments (required), own_reposts (required), stats_as_of, notes (required), created_at (required)
  metrics — id (PK, required), name (required), title (required), beat (required), source (required), source_key (required), cadence (required), gates (required), due_on, position_id (FK->positions.id), notes (required), created_at (required)
  metric_readings — id (PK, required), metric_id (FK->metrics.id, required), as_of (required), value (required), origin (required), note (required), created_at (required)

Relationships (auto-joined when include_related=True):
  positions.supersedes_id -> positions.id
  evidence.position_id -> positions.id
  forcing.position_id -> positions.id
  metrics.position_id -> positions.id
  metric_readings.metric_id -> metrics.id

Examples:
  query(table="...", filters=[{"column": "name", "op": "ILIKE", "value": "%alice%"}], limit=5)
  query(table="...", filters=[{"column": "age", "op": ">", "value": 30}], order_by="name", order_dir="DESC")
    """
    if table not in TABLES:
        return {"error": f"Unknown table '{table}'. Available: {TABLES}"}
    return await query_table(table, filters=filters or [], order_by=order_by, order_dir=order_dir, limit=limit, include_related=include_related)


@server.tool()
async def schema(table: str | None = None) -> dict:
    """Show database schema — tables, fields, types, relationships.

    Call with no args to see all tables. Pass table name for details.
    """
    return await get_schema_info(table)


@server.tool()
async def get_policy() -> dict:
    """Read the current data policy, project metadata, and data sources.

    Returns the policy that governs how data should be handled, plus
    project description and source URLs (if any). Source URLs are the
    pages used to design this schema — use them to fetch real data.
    Always check this before creating or updating records.
    """
    result = {}
    if PROJECT_JSON.exists():
        try:
            meta = _json.loads(PROJECT_JSON.read_text())
            result["policy"] = meta.get("tool_policy", "")
            result["description"] = meta.get("description", "")
            result["sources"] = meta.get("sources", [])
            if not result["policy"]:
                result["note"] = "No data policy set. Ask the user if they have preferences about data handling."
            if result["sources"]:
                result["source_hint"] = "These URLs were used to design this schema. You can fetch them to populate the database with real data."
        except Exception:
            result["policy"] = ""
    else:
        result = {"policy": "", "note": "No data policy set."}
    return result


@server.tool()
async def set_policy(policy: str) -> dict:
    """Set or update data policy rules.

    Use this when the user expresses preferences about how data should be
    handled — e.g., 'keep measurements in grams', 'show recipes as plain text',
    'don't convert units'. The policy is saved permanently and applies to all
    future operations.
    """
    _save_policy(policy)
    return {"saved": True, "policy": policy}


if __name__ == "__main__":
    server.run()
